package model

import org.apache.spark.sql.types.{ArrayType, StringType, StructField, StructType}

object Schemas {

  val biWithErnSchema: StructType = new StructType()
    .add(StructField("ern", StringType, true))
    .add(StructField("ubrn", StringType, false))
    .add(StructField("name", StringType, true))
    .add(StructField("industry_code", StringType, true))
    .add(StructField("legal_status", StringType, true))
    .add(StructField("address1", StringType, true))
    .add(StructField("address2", StringType, true))
    .add(StructField("address3", StringType, true))
    .add(StructField("address4", StringType, true))
    .add(StructField("address5", StringType, true))
    .add(StructField("postcode", StringType, true))
    .add(StructField("trading_status", StringType, true))
    .add(StructField("turnover", StringType, true))
    .add(StructField("uprn", StringType, true))
    .add(StructField("crn", StringType, true))
    .add(StructField("payerefs", ArrayType(StringType, true), true))
    .add(StructField("vatrefs", ArrayType(StringType, true), true))

  val linksLeuRowSchema: StructType = new StructType()
    .add(StructField("ubrn", StringType, false))
    .add(StructField("ern", StringType, true))
    .add(StructField("crn", StringType, true))
    .add(StructField("payerefs", ArrayType(StringType, true), true))
    .add(StructField("vatrefs", ArrayType(StringType, true), true))

  val entRowSchema: StructType = new StructType()
    .add(StructField("ern", StringType, false))
    .add(StructField("prn", StringType, false))
    .add(StructField("entref", StringType, true))
    .add(StructField("name", StringType, true))
    .add(StructField("trading_style", StringType, true))
    .add(StructField("address1", StringType, false))
    .add(StructField("address2", StringType, true))
    .add(StructField("address3", StringType, true))
    .add(StructField("address4", StringType, true))
    .add(StructField("address5", StringType, true))
    .add(StructField("postcode", StringType, false))
    .add(StructField("sic07", StringType, false))
    .add(StructField("legal_status", StringType, false))
    .add(StructField("working_props", StringType, false))

  val completeEntSchema: StructType = new StructType()
    .add(StructField("ern", StringType, false))
    .add(StructField("prn", StringType, false))
    .add(StructField("entref", StringType, true))
    .add(StructField("name", StringType, false))
    .add(StructField("trading_style", StringType, true))
    .add(StructField("address1", StringType, false))
    .add(StructField("address2", StringType, true))
    .add(StructField("address3", StringType, true))
    .add(StructField("address4", StringType, true))
    .add(StructField("address5", StringType, true))
    .add(StructField("postcode", StringType, false))
    .add(StructField("region", StringType, false))
    .add(StructField("sic07", StringType, false))
    .add(StructField("legal_status", StringType, false))
    .add(StructField("paye_empees", StringType, true))
    .add(StructField("paye_jobs", StringType, true))
    .add(StructField("cntd_turnover", StringType, true))
    .add(StructField("app_turnover", StringType, true))
    .add(StructField("std_turnover", StringType, true))
    .add(StructField("grp_turnover", StringType, true))
    .add(StructField("ent_turnover", StringType, true))
    .add(StructField("working_props", StringType, false))
    .add(StructField("employment", StringType, false))

  val adminDataSchema: StructType = new StructType()
    .add(StructField("ern", StringType, false))
    .add(StructField("paye_empees", StringType, true))
    .add(StructField("paye_jobs", StringType, true))
    .add(StructField("cntd_turnover", StringType, true))
    .add(StructField("app_turnover", StringType, true))
    .add(StructField("std_turnover", StringType, true))
    .add(StructField("grp_turnover", StringType, true))
    .add(StructField("ent_turnover", StringType, true))

  val regionSchema: StructType = new StructType()
    .add(StructField("ern", StringType, false))
    .add(StructField("paye_empees", StringType, true))
    .add(StructField("paye_jobs", StringType, true))
    .add(StructField("cntd_turnover", StringType, true))
    .add(StructField("app_turnover", StringType, true))
    .add(StructField("std_turnover", StringType, true))
    .add(StructField("grp_turnover", StringType, true))
    .add(StructField("ent_turnover", StringType, true))
    .add(StructField("region", StringType, false))

  val employmentSchema: StructType = new StructType()
    .add(StructField("ern", StringType, false))
    .add(StructField("paye_empees", StringType, true))
    .add(StructField("paye_jobs", StringType, true))
    .add(StructField("cntd_turnover", StringType, true))
    .add(StructField("app_turnover", StringType, true))
    .add(StructField("std_turnover", StringType, true))
    .add(StructField("grp_turnover", StringType, true))
    .add(StructField("ent_turnover", StringType, true))
    .add(StructField("region", StringType, false))
    .add(StructField("employment", StringType, false))

}
