package global

private object AppParams extends Serializable {

  var appParams: AppParameters = _

  def setConfiguration(p: AppParameters): Unit = appParams = p

  lazy val HBASE_LINKS_TABLE_NAME: String = appParams.HBASE_LINKS_TABLE_NAME
  lazy val HBASE_LINKS_TABLE_NAMESPACE: String = appParams.HBASE_LINKS_TABLE_NAMESPACE
  lazy val HBASE_LINKS_COLUMN_FAMILY: String = appParams.HBASE_LINKS_COLUMN_FAMILY
  lazy val PATH_TO_LINKS_HFILE: String  = appParams.PATH_TO_LINKS_HFILE

  lazy val HBASE_LEGALUNITS_TABLE_NAME: String = appParams.HBASE_LEGALUNITS_TABLE_NAME
  lazy val HBASE_LEGALUNITS_TABLE_NAMESPACE: String = appParams.HBASE_LEGALUNITS_TABLE_NAMESPACE
  lazy val HBASE_LEGALUNITS_COLUMN_FAMILY: String = appParams.HBASE_LEGALUNITS_COLUMN_FAMILY
  lazy val PATH_TO_LEGALUNITS_HFILE: String = appParams.PATH_TO_LEGALUNITS_HFILE

  lazy val HBASE_ENTERPRISE_TABLE_NAME: String = appParams.HBASE_ENTERPRISE_TABLE_NAME
  lazy val HBASE_ENTERPRISE_TABLE_NAMESPACE: String = appParams.HBASE_ENTERPRISE_TABLE_NAMESPACE
  lazy val HBASE_ENTERPRISE_COLUMN_FAMILY: String = appParams.HBASE_ENTERPRISE_COLUMN_FAMILY
  lazy val PATH_TO_ENTERPRISE_HFILE: String = appParams.PATH_TO_ENTERPRISE_HFILE

  lazy val HBASE_LOCALUNITS_TABLE_NAME: String = appParams.HBASE_LOCALUNITS_TABLE_NAME
  lazy val HBASE_LOCALUNITS_TABLE_NAMESPACE: String = appParams.HBASE_LOCALUNITS_TABLE_NAMESPACE
  lazy val HBASE_LOCALUNITS_COLUMN_FAMILY: String = appParams.HBASE_LOCALUNITS_COLUMN_FAMILY
  lazy val PATH_TO_LOCALUNITS_HFILE: String = appParams.PATH_TO_LOCALUNITS_HFILE

  lazy val HBASE_REPORTINGUNITS_TABLE_NAME: String = appParams.HBASE_REPORTINGUNITS_TABLE_NAME
  lazy val HBASE_REPORTINGUNITS_TABLE_NAMESPACE: String = appParams.HBASE_REPORTINGUNITS_TABLE_NAMESPACE
  lazy val HBASE_REPORTINGUNITS_COLUMN_FAMILY: String = appParams.HBASE_REPORTINGUNITS_COLUMN_FAMILY
  lazy val PATH_TO_REPORTINGUNITS_HFILE: String = appParams.PATH_TO_REPORTINGUNITS_HFILE

  lazy val PATH_TO_PARQUET: String = appParams.PATH_TO_PARQUET
  lazy val TIME_PERIOD: String = appParams.TIME_PERIOD

  lazy val HIVE_DB_NAME: String = appParams.HIVE_DB_NAME
  lazy val HIVE_TABLE_NAME: String = appParams.HIVE_TABLE_NAME
  lazy val HIVE_SHORT_TABLE_NAME: String = appParams.HIVE_SHORT_TABLE_NAME

  lazy val PATH_TO_PAYE: String = appParams.PATH_TO_PAYE
  lazy val PATH_TO_VAT: String = appParams.PATH_TO_VAT
  lazy val ENV: String = appParams.ENV
  lazy val ACTION: String = appParams.ACTION

  lazy val PREVIOUS_TIME_PERIOD: String = appParams.PREVIOUS_TIME_PERIOD
  lazy val PATH_TO_LEU_TO_ENT_CSV: String = appParams.PATH_TO_LEU_TO_ENT_CSV

  lazy val DEFAULT_GEO_PATH: String = appParams.DEFAULT_GEO_PATH
  lazy val DEFAULT_GEO_PATH_SHORT: String = appParams.DEFAULT_GEO_PATH_SHORT

  lazy val PATH_TO_GEO: String = DEFAULT_GEO_PATH
  lazy val PATH_TO_GEO_SHORT: String = DEFAULT_GEO_PATH_SHORT

}